### ISSUE TITLE
Error in the names of classes.json in meta

### ISSUE THREAD

**Issue by alexindris** [codethesaurus/codethesaur.us#363]
# Expected Behavior

In the classes.json inside the meta we can see the following issues:
 
 "packages": {
      "name": "Packages",
      "code": ""
    }

 "private_variables": {
      "name": "Defining private variables",
      "code": ""
    },
# Actual Behavior

    "packages": {
      "name": "Normal class",
      "code": ""
    },

    "private_variables": {
      "name": "Defining public variables",
      "code": ""
    },
# Steps to Reproduce the Problem

1. Execute the app
2.  Check Typescript classes for example
3.  See that the texts are wrong

# Additional Info

![image](https://user-images.githubusercontent.com/46220983/137093600-8091d72d-5d36-4000-a222-045b69e4d007.png)

**Comment by geekygirlsarah** [comment]
Oops, I swore we fixed this, but guess not! Thanks for reporting this (and fixing it)!

**Comment by alexindris** [comment]
Btw could you please mark it so that it counts for the hacktoberfest thanks

**Comment by geekygirlsarah** [comment]
It'll count whether I mark it that way or not because the whole project is opted in. (See [this](https://hacktoberfest.digitalocean.com/resources/maintainers).)

I usually add it to issues for people searching, since some look for issues containing "hacktoberfest" so they know what to work on. I can add it but it really has no effect, it's only the PRs accepted/merged that count towards the goal, not issues closed.

**Comment by alexindris** [comment]
Ohh okay thaks is my first time and i didn't knew. Thanks

**Comment by geekygirlsarah** [comment]
Understandable. This is Code Thesaurus's 4th Hacktoberfest (though only 2nd where I've had outside contributors), and I definitely WANT people to contribute AND get the credit, so I do my best to set it up right!
