### ISSUE TITLE
[Javascript] Add input/output

### ISSUE THREAD

**Issue by ulyssear** [codethesaurus/codethesaur.us#595]
# Description

Add "input/output" concept for javascript (ECMAScript 2009, 2020, 2021 and 2023)

# Directions

Same directions than issues about adding a concept (#583 for example).

# Additional Information

I can work on this issue. As I started Hacktoberfest with this repository, I'm enjoying it ^^

**Comment by geekygirlsarah** [comment]
Sounds good @ulyssear, I'll assign you!

**Comment by ulyssear** [comment]
I began the issue today and I'm confused about some points (see below).

![image](https://user-images.githubusercontent.com/11415595/196392696-4e98d782-5da9-4580-9216-6c455fe36337.png)

Firstly, JavaScript syntax highlighting is either uninteresting or incomprehensible.
In the screenshot shown, only two keywords are colored ("const" and "delete"), and the "delete" method, due to the keyword, is the only method colored.
A new issue may be created to deal with this.

![image](https://user-images.githubusercontent.com/11415595/196394381-36241c5d-088a-469c-9a20-44cfb27afa27.png)

Lastly, JavaScript has a native method for manipulating WebSockets. However, these are not network sockets. Do I put code snippets about WebSockets? Otherwise, we can add a Node.js module dealing with network sockets (`net` module for example).

Thanks in advance for your answer! :)

**Comment by cafce25** [comment]
You're right about the highlighting but I think it's hard to get better automated highlighting cause the snippets of code are so short and there is almost no context. Although your string is highlighted as well, but since we're just using the default `pygments` colorscheme that's barely noticeable. 

I've created #602 to track the syntax issue

I think websockets should go into their own concepts, network sockets here refer to bare tcp/ip sockets.
Since there are no concepts about websockets yet you'd need to create new ones in [the meta file](https://github.com/codethesaurus/codethesaur.us/blob/main/web/thesauruses/_meta/io.json) first. Then you can just use your newly created keys.
You can either add them  into the "Network IO" category or just create a new one, your choice if you decide to add them.

**Comment by geekygirlsarah** [comment]
For the syntax highlighting, aside from fixing it in the [Pygments](https://github.com/pygments/pygments) project or finding a new highlighter, I'm not sure what we can do. I definitely do NOT recommend making a new highlighter, lol.

As for Websockets, I think it crossed my mind but I dismissed it thinking it was only a JavaScript thing, but I guess you implement the other side in whatever language you want. So yeah, I could see it becoming a new IO section in the meta file.
