### ISSUE TITLE
[Minor feature] Get the template of a concept from the compare page

### ISSUE THREAD

**Issue by ulyssear** [codethesaurus/codethesaur.us#628]
# Description

Add a link, like the current link "Want to add or correct information for ____?", which permits the user to get the whole template of a concept.
With this feature, the user can easily update the concept from the template if needed.

# Requirements

* Add a link "Want to get an empty template of this concept?" which generates a template or redirects to a raw file of the template (like the link "Want to add or correct information for ____?" does).

# Additional Notes

(from @geekygirlsarah: This is for a _filled_ out template that contains existing and not existing data.)

**Comment by monkeywithacupcake** [comment]
cool idea

**Comment by geekygirlsarah** [comment]
This sounds closely related to #605, though I guess different enough it makes sense. Though the problem is you wouldn't land on this page without picking an existing language/concept because the home page blocks it. You could get to it through URL hacking, but at that point if you want the template, you could just get it through something like #605. 

If the information was there, what would the template help with since it would be empty? I'd think the existing Github link takes you essentially to a filled in template already.

(I'm not shooting this down, but mostly just wanting to make sure I'm not missing part of this idea)

**Comment by ulyssear** [comment]
> This sounds closely related to #605, though I guess different enough it makes sense. Though the problem is you wouldn't land on this page without picking an existing language/concept because the home page blocks it. You could get to it through URL hacking, but at that point if you want the template, you could just get it through something like #605.
> 
> If the information was there, what would the template help with since it would be empty? I'd think the existing Github link takes you essentially to a filled in template already.
> 
> (I'm not shooting this down, but mostly just wanting to make sure I'm not missing part of this idea)

I updated the PR, I think it will be better now!
I replaced the link to the raw file in GitHub with a link showing the modal showing the whole template (which is a merge between the empty template and the current template).

**Comment by ulyssear** [comment]
If there is something to fix (or add) to merge the PR / close this issue, I'm still available !
