### ISSUE TITLE
500 Server Error when looking up concepts

### ISSUE THREAD

**Issue by monkeywithacupcake** [codethesaurus/codethesaur.us#673]
# Expected Behavior

When user picks a language concept and languages on the left or a single language on the right, they should get the code pages

# Actual Behavior

I'm getting a 500 Server Error

# Steps to Reproduce the Problem

1. go to [the site](https://codethesaur.us)
1. use the boxes to pick a concept and language
1. hit go->

# Additional Info

I'm on Safari

<img width="800" alt="Screen Shot 2023-08-08 at 20 09 05" src="https://github.com/codethesaurus/codethesaur.us/assets/7316730/548328c7-044a-4666-b21d-1ffeb6c18e66">

**Comment by geekygirlsarah** [comment]
Hmm... that's definitely not supposed to be happening and I thought it was working. I'll try digging into it shortly (though am on a work trip at a conference for the next 24 hours so not sure how much I can do for now)

**Comment by monkeywithacupcake** [comment]
also getting the 500 when clicking "about" in the nabber 
so it is something referencing the backend. haven't found the actual issue yet

**Comment by geekygirlsarah** [comment]
So it's giving a 500 server error when a page doesn't seem to exist, in this case, usually `/favicon.ico`. I'm able to replicate it locally if I open `settings.py`, comment out lines 28-31, and set `DEBUG = True` (or `False` to see the difference) and `SECURE_SSL_REDIRECT = False`.

So it looks like the 404 handler isn't working right, or the URL router isn't working right, and that's about all I've managed to figure out so far because I have to go to bed. I'll see if I can poke at this more if you haven't solved it before me.

**Comment by monkeywithacupcake** [comment]
I don't know what is happening. Perhaps there is an issue on Django on heroku?

I've been trying to convince the javascript console to give me something useful, but all I get is that every end point that is not  `/` (the index) that hits on [codethesaur.us](https://codethesaur.us/) is returning 500 

the endpoints that hit to [docs](https://docs.codethesaur.us) work fine.

**Comment by geekygirlsarah** [comment]
Docs are hosted in Netlify and is basically a Markdown-to-HTML system. It's separate from the main site.

The web dev console won't give you details because it's not a API/JSON/frontend issue, it's entirely on the backend. By changing the settings in my last comment, I got the errors to show up in my Python console running it locally.

I haven't had time to look at it this week but maybe after work today or sometime tomorrow I'll get to it if you don't figure it out first.

**Comment by monkeywithacupcake** [comment]
I cannot fix this on my local machine. I cannot get the same behavior. When I change `DEBUG = False`, I can still load about (if I keep `SECURE_SSL_REDIRECT = False #not DEBUG`)

Perhaps the heroku needs a refresh? Hopefully there are logs?  If not, SO has some suggestion to add `DEBUG_PROPAGATE_EXCEPTIONS = True` to still get logs on heroku when things break.

**Comment by geekygirlsarah** [comment]
Alright, I stand corrected. It seems to sometimes happen and sometimes not, and I haven't quite figured out the pattern of conditions to tweak to get it to happen every time. It's becoming a pain to debug!

Restarting the Heroku app didn't help. Heck, doing that fixed it, then it broke again. I'm definitely boggled.

**Comment by geekygirlsarah** [comment]
Alright, I _think_ it's working from all that I can tell. Want to confirm?

**Comment by monkeywithacupcake** [comment]
working - awesome

**Comment by geekygirlsarah** [comment]
Sweet! And I added in a unit test that should hopefully check this as well for the future
